//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Survey.Web.UI.GlobalWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GlobalWebService.GlobalSoap")]
    public interface GlobalSoap {
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConfigXML", ReplyAction="*")]
        ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLResponse GetConfigXML(ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConfigXML", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLResponse> GetConfigXMLAsync(ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        ITI.Survey.Web.UI.GlobalWebService.LoginResponse Login(ITI.Survey.Web.UI.GlobalWebService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.GlobalWebService.LoginResponse> LoginAsync(ITI.Survey.Web.UI.GlobalWebService.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConfigXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConfigXML", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLRequestBody Body;
        
        public GetConfigXMLRequest() {
        }
        
        public GetConfigXMLRequest(ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetConfigXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public GetConfigXMLRequestBody() {
        }
        
        public GetConfigXMLRequestBody(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConfigXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConfigXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLResponseBody Body;
        
        public GetConfigXMLResponse() {
        }
        
        public GetConfigXMLResponse(ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetConfigXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetConfigXMLResult;
        
        public GetConfigXMLResponseBody() {
        }
        
        public GetConfigXMLResponseBody(string GetConfigXMLResult) {
            this.GetConfigXMLResult = GetConfigXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.GlobalWebService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ITI.Survey.Web.UI.GlobalWebService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string userId, string password) {
            this.userId = userId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.GlobalWebService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ITI.Survey.Web.UI.GlobalWebService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GlobalSoapChannel : ITI.Survey.Web.UI.GlobalWebService.GlobalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GlobalSoapClient : System.ServiceModel.ClientBase<ITI.Survey.Web.UI.GlobalWebService.GlobalSoap>, ITI.Survey.Web.UI.GlobalWebService.GlobalSoap {
        
        public GlobalSoapClient() {
        }
        
        public GlobalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GlobalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlobalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlobalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLResponse ITI.Survey.Web.UI.GlobalWebService.GlobalSoap.GetConfigXML(ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLRequest request) {
            return base.Channel.GetConfigXML(request);
        }
        
        public string GetConfigXML(string userId) {
            ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLRequest inValue = new ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLRequest();
            inValue.Body = new ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLRequestBody();
            inValue.Body.userId = userId;
            ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLResponse retVal = ((ITI.Survey.Web.UI.GlobalWebService.GlobalSoap)(this)).GetConfigXML(inValue);
            return retVal.Body.GetConfigXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLResponse> ITI.Survey.Web.UI.GlobalWebService.GlobalSoap.GetConfigXMLAsync(ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLRequest request) {
            return base.Channel.GetConfigXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLResponse> GetConfigXMLAsync(string userId) {
            ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLRequest inValue = new ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLRequest();
            inValue.Body = new ITI.Survey.Web.UI.GlobalWebService.GetConfigXMLRequestBody();
            inValue.Body.userId = userId;
            return ((ITI.Survey.Web.UI.GlobalWebService.GlobalSoap)(this)).GetConfigXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.Survey.Web.UI.GlobalWebService.LoginResponse ITI.Survey.Web.UI.GlobalWebService.GlobalSoap.Login(ITI.Survey.Web.UI.GlobalWebService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string userId, string password) {
            ITI.Survey.Web.UI.GlobalWebService.LoginRequest inValue = new ITI.Survey.Web.UI.GlobalWebService.LoginRequest();
            inValue.Body = new ITI.Survey.Web.UI.GlobalWebService.LoginRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            ITI.Survey.Web.UI.GlobalWebService.LoginResponse retVal = ((ITI.Survey.Web.UI.GlobalWebService.GlobalSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.GlobalWebService.LoginResponse> ITI.Survey.Web.UI.GlobalWebService.GlobalSoap.LoginAsync(ITI.Survey.Web.UI.GlobalWebService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.Survey.Web.UI.GlobalWebService.LoginResponse> LoginAsync(string userId, string password) {
            ITI.Survey.Web.UI.GlobalWebService.LoginRequest inValue = new ITI.Survey.Web.UI.GlobalWebService.LoginRequest();
            inValue.Body = new ITI.Survey.Web.UI.GlobalWebService.LoginRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            return ((ITI.Survey.Web.UI.GlobalWebService.GlobalSoap)(this)).LoginAsync(inValue);
        }
    }
}
