//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Survey.Web.UI.StackingWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StackingWebService.StackingSoap")]
    public interface StackingSoap {
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillContCardByIdAndCardMode", ReplyAction="*")]
        ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeResponse FillContCardByIdAndCardMode(ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillContCardByIdAndCardMode", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeResponse> FillContCardByIdAndCardModeAsync(ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillContainerDuration", ReplyAction="*")]
        ITI.Survey.Web.UI.StackingWebService.FillContainerDurationResponse FillContainerDuration(ITI.Survey.Web.UI.StackingWebService.FillContainerDurationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillContainerDuration", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContainerDurationResponse> FillContainerDurationAsync(ITI.Survey.Web.UI.StackingWebService.FillContainerDurationRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillContInOutById", ReplyAction="*")]
        ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdResponse FillContInOutById(ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillContInOutById", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdResponse> FillContInOutByIdAsync(ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillContInOutByContainerNumber", ReplyAction="*")]
        ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberResponse FillContInOutByContainerNumber(ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillContInOutByContainerNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberResponse> FillContInOutByContainerNumberAsync(ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitKartuBongkar", ReplyAction="*")]
        ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarResponse SubmitKartuBongkar(ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitKartuBongkar", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarResponse> SubmitKartuBongkarAsync(ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitNoMobil", ReplyAction="*")]
        ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilResponse SubmitNoMobil(ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitNoMobil", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilResponse> SubmitNoMobilAsync(ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitBlokMove", ReplyAction="*")]
        ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveResponse SubmitBlokMove(ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitBlokMove", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveResponse> SubmitBlokMoveAsync(ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillContInOutByContainerForStock", ReplyAction="*")]
        ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockResponse FillContInOutByContainerForStock(ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillContInOutByContainerForStock", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockResponse> FillContInOutByContainerForStockAsync(ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillContInOutByBlokForStock", ReplyAction="*")]
        ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockResponse FillContInOutByBlokForStock(ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillContInOutByBlokForStock", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockResponse> FillContInOutByBlokForStockAsync(ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FillContCardByIdAndCardModeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FillContCardByIdAndCardMode", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeRequestBody Body;
        
        public FillContCardByIdAndCardModeRequest() {
        }
        
        public FillContCardByIdAndCardModeRequest(ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FillContCardByIdAndCardModeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cardMode;
        
        public FillContCardByIdAndCardModeRequestBody() {
        }
        
        public FillContCardByIdAndCardModeRequestBody(string userId, long id, string cardMode) {
            this.userId = userId;
            this.id = id;
            this.cardMode = cardMode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FillContCardByIdAndCardModeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FillContCardByIdAndCardModeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeResponseBody Body;
        
        public FillContCardByIdAndCardModeResponse() {
        }
        
        public FillContCardByIdAndCardModeResponse(ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FillContCardByIdAndCardModeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FillContCardByIdAndCardModeResult;
        
        public FillContCardByIdAndCardModeResponseBody() {
        }
        
        public FillContCardByIdAndCardModeResponseBody(string FillContCardByIdAndCardModeResult) {
            this.FillContCardByIdAndCardModeResult = FillContCardByIdAndCardModeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FillContainerDurationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FillContainerDuration", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.FillContainerDurationRequestBody Body;
        
        public FillContainerDurationRequest() {
        }
        
        public FillContainerDurationRequest(ITI.Survey.Web.UI.StackingWebService.FillContainerDurationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FillContainerDurationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string customerCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string size;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string condition;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int minDuration;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sortBy;
        
        public FillContainerDurationRequestBody() {
        }
        
        public FillContainerDurationRequestBody(string userId, string customerCode, string size, string type, string condition, int minDuration, string sortBy) {
            this.userId = userId;
            this.customerCode = customerCode;
            this.size = size;
            this.type = type;
            this.condition = condition;
            this.minDuration = minDuration;
            this.sortBy = sortBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FillContainerDurationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FillContainerDurationResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.FillContainerDurationResponseBody Body;
        
        public FillContainerDurationResponse() {
        }
        
        public FillContainerDurationResponse(ITI.Survey.Web.UI.StackingWebService.FillContainerDurationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FillContainerDurationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FillContainerDurationResult;
        
        public FillContainerDurationResponseBody() {
        }
        
        public FillContainerDurationResponseBody(string FillContainerDurationResult) {
            this.FillContainerDurationResult = FillContainerDurationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FillContInOutByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FillContInOutById", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdRequestBody Body;
        
        public FillContInOutByIdRequest() {
        }
        
        public FillContInOutByIdRequest(ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FillContInOutByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long contInOutId;
        
        public FillContInOutByIdRequestBody() {
        }
        
        public FillContInOutByIdRequestBody(string userId, long contInOutId) {
            this.userId = userId;
            this.contInOutId = contInOutId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FillContInOutByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FillContInOutByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdResponseBody Body;
        
        public FillContInOutByIdResponse() {
        }
        
        public FillContInOutByIdResponse(ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FillContInOutByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FillContInOutByIdResult;
        
        public FillContInOutByIdResponseBody() {
        }
        
        public FillContInOutByIdResponseBody(string FillContInOutByIdResult) {
            this.FillContInOutByIdResult = FillContInOutByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FillContInOutByContainerNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FillContInOutByContainerNumber", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberRequestBody Body;
        
        public FillContInOutByContainerNumberRequest() {
        }
        
        public FillContInOutByContainerNumberRequest(ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FillContInOutByContainerNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string containerNumber;
        
        public FillContInOutByContainerNumberRequestBody() {
        }
        
        public FillContInOutByContainerNumberRequestBody(string userId, string containerNumber) {
            this.userId = userId;
            this.containerNumber = containerNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FillContInOutByContainerNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FillContInOutByContainerNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberResponseBody Body;
        
        public FillContInOutByContainerNumberResponse() {
        }
        
        public FillContInOutByContainerNumberResponse(ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FillContInOutByContainerNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FillContInOutByContainerNumberResult;
        
        public FillContInOutByContainerNumberResponseBody() {
        }
        
        public FillContInOutByContainerNumberResponseBody(string FillContInOutByContainerNumberResult) {
            this.FillContInOutByContainerNumberResult = FillContInOutByContainerNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitKartuBongkarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitKartuBongkar", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarRequestBody Body;
        
        public SubmitKartuBongkarRequest() {
        }
        
        public SubmitKartuBongkarRequest(ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitKartuBongkarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public SubmitKartuBongkarRequestBody() {
        }
        
        public SubmitKartuBongkarRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitKartuBongkarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitKartuBongkarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarResponseBody Body;
        
        public SubmitKartuBongkarResponse() {
        }
        
        public SubmitKartuBongkarResponse(ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitKartuBongkarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubmitKartuBongkarResult;
        
        public SubmitKartuBongkarResponseBody() {
        }
        
        public SubmitKartuBongkarResponseBody(string SubmitKartuBongkarResult) {
            this.SubmitKartuBongkarResult = SubmitKartuBongkarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitNoMobilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitNoMobil", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilRequestBody Body;
        
        public SubmitNoMobilRequest() {
        }
        
        public SubmitNoMobilRequest(ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitNoMobilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public SubmitNoMobilRequestBody() {
        }
        
        public SubmitNoMobilRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitNoMobilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitNoMobilResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilResponseBody Body;
        
        public SubmitNoMobilResponse() {
        }
        
        public SubmitNoMobilResponse(ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitNoMobilResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubmitNoMobilResult;
        
        public SubmitNoMobilResponseBody() {
        }
        
        public SubmitNoMobilResponseBody(string SubmitNoMobilResult) {
            this.SubmitNoMobilResult = SubmitNoMobilResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitBlokMoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitBlokMove", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveRequestBody Body;
        
        public SubmitBlokMoveRequest() {
        }
        
        public SubmitBlokMoveRequest(ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitBlokMoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public SubmitBlokMoveRequestBody() {
        }
        
        public SubmitBlokMoveRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitBlokMoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitBlokMoveResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveResponseBody Body;
        
        public SubmitBlokMoveResponse() {
        }
        
        public SubmitBlokMoveResponse(ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitBlokMoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubmitBlokMoveResult;
        
        public SubmitBlokMoveResponseBody() {
        }
        
        public SubmitBlokMoveResponseBody(string SubmitBlokMoveResult) {
            this.SubmitBlokMoveResult = SubmitBlokMoveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FillContInOutByContainerForStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FillContInOutByContainerForStock", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockRequestBody Body;
        
        public FillContInOutByContainerForStockRequest() {
        }
        
        public FillContInOutByContainerForStockRequest(ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FillContInOutByContainerForStockRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string containerNumber;
        
        public FillContInOutByContainerForStockRequestBody() {
        }
        
        public FillContInOutByContainerForStockRequestBody(string userId, string containerNumber) {
            this.userId = userId;
            this.containerNumber = containerNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FillContInOutByContainerForStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FillContInOutByContainerForStockResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockResponseBody Body;
        
        public FillContInOutByContainerForStockResponse() {
        }
        
        public FillContInOutByContainerForStockResponse(ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FillContInOutByContainerForStockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FillContInOutByContainerForStockResult;
        
        public FillContInOutByContainerForStockResponseBody() {
        }
        
        public FillContInOutByContainerForStockResponseBody(string FillContInOutByContainerForStockResult) {
            this.FillContInOutByContainerForStockResult = FillContInOutByContainerForStockResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FillContInOutByBlokForStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FillContInOutByBlokForStock", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockRequestBody Body;
        
        public FillContInOutByBlokForStockRequest() {
        }
        
        public FillContInOutByBlokForStockRequest(ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FillContInOutByBlokForStockRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string blok;
        
        public FillContInOutByBlokForStockRequestBody() {
        }
        
        public FillContInOutByBlokForStockRequestBody(string userId, string blok) {
            this.userId = userId;
            this.blok = blok;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FillContInOutByBlokForStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FillContInOutByBlokForStockResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockResponseBody Body;
        
        public FillContInOutByBlokForStockResponse() {
        }
        
        public FillContInOutByBlokForStockResponse(ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FillContInOutByBlokForStockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FillContInOutByBlokForStockResult;
        
        public FillContInOutByBlokForStockResponseBody() {
        }
        
        public FillContInOutByBlokForStockResponseBody(string FillContInOutByBlokForStockResult) {
            this.FillContInOutByBlokForStockResult = FillContInOutByBlokForStockResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StackingSoapChannel : ITI.Survey.Web.UI.StackingWebService.StackingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StackingSoapClient : System.ServiceModel.ClientBase<ITI.Survey.Web.UI.StackingWebService.StackingSoap>, ITI.Survey.Web.UI.StackingWebService.StackingSoap {
        
        public StackingSoapClient() {
        }
        
        public StackingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StackingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StackingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StackingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeResponse ITI.Survey.Web.UI.StackingWebService.StackingSoap.FillContCardByIdAndCardMode(ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeRequest request) {
            return base.Channel.FillContCardByIdAndCardMode(request);
        }
        
        public string FillContCardByIdAndCardMode(string userId, long id, string cardMode) {
            ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeRequest inValue = new ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.id = id;
            inValue.Body.cardMode = cardMode;
            ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeResponse retVal = ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).FillContCardByIdAndCardMode(inValue);
            return retVal.Body.FillContCardByIdAndCardModeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeResponse> ITI.Survey.Web.UI.StackingWebService.StackingSoap.FillContCardByIdAndCardModeAsync(ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeRequest request) {
            return base.Channel.FillContCardByIdAndCardModeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeResponse> FillContCardByIdAndCardModeAsync(string userId, long id, string cardMode) {
            ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeRequest inValue = new ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.FillContCardByIdAndCardModeRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.id = id;
            inValue.Body.cardMode = cardMode;
            return ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).FillContCardByIdAndCardModeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.Survey.Web.UI.StackingWebService.FillContainerDurationResponse ITI.Survey.Web.UI.StackingWebService.StackingSoap.FillContainerDuration(ITI.Survey.Web.UI.StackingWebService.FillContainerDurationRequest request) {
            return base.Channel.FillContainerDuration(request);
        }
        
        public string FillContainerDuration(string userId, string customerCode, string size, string type, string condition, int minDuration, string sortBy) {
            ITI.Survey.Web.UI.StackingWebService.FillContainerDurationRequest inValue = new ITI.Survey.Web.UI.StackingWebService.FillContainerDurationRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.FillContainerDurationRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.customerCode = customerCode;
            inValue.Body.size = size;
            inValue.Body.type = type;
            inValue.Body.condition = condition;
            inValue.Body.minDuration = minDuration;
            inValue.Body.sortBy = sortBy;
            ITI.Survey.Web.UI.StackingWebService.FillContainerDurationResponse retVal = ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).FillContainerDuration(inValue);
            return retVal.Body.FillContainerDurationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContainerDurationResponse> ITI.Survey.Web.UI.StackingWebService.StackingSoap.FillContainerDurationAsync(ITI.Survey.Web.UI.StackingWebService.FillContainerDurationRequest request) {
            return base.Channel.FillContainerDurationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContainerDurationResponse> FillContainerDurationAsync(string userId, string customerCode, string size, string type, string condition, int minDuration, string sortBy) {
            ITI.Survey.Web.UI.StackingWebService.FillContainerDurationRequest inValue = new ITI.Survey.Web.UI.StackingWebService.FillContainerDurationRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.FillContainerDurationRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.customerCode = customerCode;
            inValue.Body.size = size;
            inValue.Body.type = type;
            inValue.Body.condition = condition;
            inValue.Body.minDuration = minDuration;
            inValue.Body.sortBy = sortBy;
            return ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).FillContainerDurationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdResponse ITI.Survey.Web.UI.StackingWebService.StackingSoap.FillContInOutById(ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdRequest request) {
            return base.Channel.FillContInOutById(request);
        }
        
        public string FillContInOutById(string userId, long contInOutId) {
            ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdRequest inValue = new ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.contInOutId = contInOutId;
            ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdResponse retVal = ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).FillContInOutById(inValue);
            return retVal.Body.FillContInOutByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdResponse> ITI.Survey.Web.UI.StackingWebService.StackingSoap.FillContInOutByIdAsync(ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdRequest request) {
            return base.Channel.FillContInOutByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdResponse> FillContInOutByIdAsync(string userId, long contInOutId) {
            ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdRequest inValue = new ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.FillContInOutByIdRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.contInOutId = contInOutId;
            return ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).FillContInOutByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberResponse ITI.Survey.Web.UI.StackingWebService.StackingSoap.FillContInOutByContainerNumber(ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberRequest request) {
            return base.Channel.FillContInOutByContainerNumber(request);
        }
        
        public string FillContInOutByContainerNumber(string userId, string containerNumber) {
            ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberRequest inValue = new ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.containerNumber = containerNumber;
            ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberResponse retVal = ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).FillContInOutByContainerNumber(inValue);
            return retVal.Body.FillContInOutByContainerNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberResponse> ITI.Survey.Web.UI.StackingWebService.StackingSoap.FillContInOutByContainerNumberAsync(ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberRequest request) {
            return base.Channel.FillContInOutByContainerNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberResponse> FillContInOutByContainerNumberAsync(string userId, string containerNumber) {
            ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberRequest inValue = new ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerNumberRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.containerNumber = containerNumber;
            return ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).FillContInOutByContainerNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarResponse ITI.Survey.Web.UI.StackingWebService.StackingSoap.SubmitKartuBongkar(ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarRequest request) {
            return base.Channel.SubmitKartuBongkar(request);
        }
        
        public string SubmitKartuBongkar(string xml) {
            ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarRequest inValue = new ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarRequestBody();
            inValue.Body.xml = xml;
            ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarResponse retVal = ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).SubmitKartuBongkar(inValue);
            return retVal.Body.SubmitKartuBongkarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarResponse> ITI.Survey.Web.UI.StackingWebService.StackingSoap.SubmitKartuBongkarAsync(ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarRequest request) {
            return base.Channel.SubmitKartuBongkarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarResponse> SubmitKartuBongkarAsync(string xml) {
            ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarRequest inValue = new ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.SubmitKartuBongkarRequestBody();
            inValue.Body.xml = xml;
            return ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).SubmitKartuBongkarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilResponse ITI.Survey.Web.UI.StackingWebService.StackingSoap.SubmitNoMobil(ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilRequest request) {
            return base.Channel.SubmitNoMobil(request);
        }
        
        public string SubmitNoMobil(string xml) {
            ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilRequest inValue = new ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilRequestBody();
            inValue.Body.xml = xml;
            ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilResponse retVal = ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).SubmitNoMobil(inValue);
            return retVal.Body.SubmitNoMobilResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilResponse> ITI.Survey.Web.UI.StackingWebService.StackingSoap.SubmitNoMobilAsync(ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilRequest request) {
            return base.Channel.SubmitNoMobilAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilResponse> SubmitNoMobilAsync(string xml) {
            ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilRequest inValue = new ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.SubmitNoMobilRequestBody();
            inValue.Body.xml = xml;
            return ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).SubmitNoMobilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveResponse ITI.Survey.Web.UI.StackingWebService.StackingSoap.SubmitBlokMove(ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveRequest request) {
            return base.Channel.SubmitBlokMove(request);
        }
        
        public string SubmitBlokMove(string xml) {
            ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveRequest inValue = new ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveRequestBody();
            inValue.Body.xml = xml;
            ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveResponse retVal = ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).SubmitBlokMove(inValue);
            return retVal.Body.SubmitBlokMoveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveResponse> ITI.Survey.Web.UI.StackingWebService.StackingSoap.SubmitBlokMoveAsync(ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveRequest request) {
            return base.Channel.SubmitBlokMoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveResponse> SubmitBlokMoveAsync(string xml) {
            ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveRequest inValue = new ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.SubmitBlokMoveRequestBody();
            inValue.Body.xml = xml;
            return ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).SubmitBlokMoveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockResponse ITI.Survey.Web.UI.StackingWebService.StackingSoap.FillContInOutByContainerForStock(ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockRequest request) {
            return base.Channel.FillContInOutByContainerForStock(request);
        }
        
        public string FillContInOutByContainerForStock(string userId, string containerNumber) {
            ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockRequest inValue = new ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.containerNumber = containerNumber;
            ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockResponse retVal = ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).FillContInOutByContainerForStock(inValue);
            return retVal.Body.FillContInOutByContainerForStockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockResponse> ITI.Survey.Web.UI.StackingWebService.StackingSoap.FillContInOutByContainerForStockAsync(ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockRequest request) {
            return base.Channel.FillContInOutByContainerForStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockResponse> FillContInOutByContainerForStockAsync(string userId, string containerNumber) {
            ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockRequest inValue = new ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.FillContInOutByContainerForStockRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.containerNumber = containerNumber;
            return ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).FillContInOutByContainerForStockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockResponse ITI.Survey.Web.UI.StackingWebService.StackingSoap.FillContInOutByBlokForStock(ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockRequest request) {
            return base.Channel.FillContInOutByBlokForStock(request);
        }
        
        public string FillContInOutByBlokForStock(string userId, string blok) {
            ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockRequest inValue = new ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.blok = blok;
            ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockResponse retVal = ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).FillContInOutByBlokForStock(inValue);
            return retVal.Body.FillContInOutByBlokForStockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockResponse> ITI.Survey.Web.UI.StackingWebService.StackingSoap.FillContInOutByBlokForStockAsync(ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockRequest request) {
            return base.Channel.FillContInOutByBlokForStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockResponse> FillContInOutByBlokForStockAsync(string userId, string blok) {
            ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockRequest inValue = new ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockRequest();
            inValue.Body = new ITI.Survey.Web.UI.StackingWebService.FillContInOutByBlokForStockRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.blok = blok;
            return ((ITI.Survey.Web.UI.StackingWebService.StackingSoap)(this)).FillContInOutByBlokForStockAsync(inValue);
        }
    }
}
